### ISSUE TITLE
Profile on Windows broken?

### ISSUE THREAD

**Issue by theauheral** [phillipdupuis/dtale-desktop#11]
Hello,
First of all, excellent work. I love it. I have tried different datasets and two different computers both running windows and I keep getting the same error when trying out Profile. I tried with Python versions 3.7.6.4 and 3.8.7. I am using the covid dataset available with D-Tale Desktop that I downloaded.

File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 756031: character maps to <undefined>

I am about to try on Linux.

**Comment by theauheral** [comment]
Failed too on a linux host but it looked different.


File "/home/myuser/myproject/venv/lib/python3.7/site-packages/dtale_desktop/models.py", line 423, in build_profile_report
    raise HTTPException(status_code=500, detail=str(e))
fastapi.exceptions.HTTPException
INFO:     ip address - "GET /node/build-profile-report/783a6f0498e02303c0e58dbcecc1f862/ HTTP/1.1" 500 Internal Server Error

**Comment by phillipdupuis** [comment]
Ah I'm sorry, that's annoying -- that pandas-profiling report has a tendency to take absolutely ages with certain datasets and sometimes crash, so I have it running in a separate process, but it's a bit fragile. I'll hop on a windows computer tomorrow to debug + release a fix

**Comment by phillipdupuis** [comment]
I think this should be good to go now, if you `pip install -U dtaledesktop` it should grab v0.1.2

I tested it out on windows and it seemed fine, but I can leave this open until you can try it out and confirm it's working

**Comment by theauheral** [comment]
It works! Thank you very much! Not sure if you did anything else but the performance looks improved too overall (faster load times of both dtale and profile).
