### ISSUE TITLE
Error when trying to launch the app

### ISSUE THREAD

**Issue by robin2010liu** [phillipdupuis/dtale-desktop#7]
I tried to run it on a mac, but got error message like this. Any ideas? Thanks!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robin/Library/Python/3.7/lib/python/site-packages/dtale_desktop/__init__.py", line 64, in run
    app.run()
  File "/Users/robin/Library/Python/3.7/lib/python/site-packages/dtale_desktop/app.py", line 74, in run
    launch_browser_opener(f"http://{settings.HOST}:{settings.PORT}")
  File "/Users/robin/Library/Python/3.7/lib/python/site-packages/dtale_desktop/subprocesses.py", line 55, in launch_browser_opener
    subprocess.Popen(["dtaledesktop_open_browser", url])
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dtaledesktop_open_browser': 'dtaledesktop_open_browser'

**Comment by phillipdupuis** [comment]
Hmm that's strange, sorry about that. Can you type this into your terminal and post what it prints out?
`$ which dtaledesktop_open_browser`

In the meantime, I think a workaround might be to run it like this:
`$ DTALEDESKTOP_DISABLE_OPEN_BROWSER=true dtaledesktop`

That environment variable prevents the 'open_browser' subprocess from running on startup. You'll just need to grab the URL from the `INFO:     Uvicorn running on <url> (Press CTRL+C to quit)` line that gets printed to the console and then paste it into your browser.

**Comment by robin2010liu** [comment]
Thanks for fast reply!
$ which dtaledesktop_open_browser
returns nothing,
$ DTALEDESKTOP_DISABLE_OPEN_BROWSER=true dtaledesktop
returns
-bash: dtaledesktop: command not found
and if open python and import the module to run, it will show the above error.
It seems I installed successfully, let me try reinstall it.

**Comment by phillipdupuis** [comment]
Hm okay :/ it may be worth looking at some of the answers here, since it seems like your issue is that it can't find any of the executables: https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

Does `$ which python` return anything?

**Comment by robin2010liu** [comment]
It looks like the executable is installed in a folder which is not in the 'PATH'. I moved the executables to /usr/local/bin and it worked. Thanks for your help! Great work!

**Comment by phillipdupuis** [comment]
Oh awesome! And no problem :) I'll close this one out in that case
